services:
  # Web Service
  - type: web
    name: clinica-inventario-ia
    runtime: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y wget gnupg
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      apt-get update
      apt-get install -y google-chrome-stable fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release xdg-utils
      rm -rf /var/lib/apt/lists/*
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PGHOST
        fromDatabase:
          name: clinica-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: clinica-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: clinica-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: clinica-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: clinica-db
          property: password
      - key: OPENAI_API_KEY
        sync: false # Deberás configurar esto manualmente en Render
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable

databases:
  - name: clinica-db
    databaseName: clinica_inventario
    user: clinica_user
    plan: free # Puedes cambiar a un plan pagado si necesitas más recursos
